name: CD

on: pull_request

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: xcodebuild test -project tick.xcodeproj -scheme tickTests -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
