name: Unit & UI Tests

on: pull_request

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
    - name: Unit Tests
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'unit_tests'
  ui-tests:
    runs-on: macos-latest
    steps:
    - name: UI Tests
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'ui_tests'
